name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      steps:
      # 1️⃣ Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Install system dependencies
      - name: Install system dependencies
        run: |
          gem install sassc -v 2.4.0   # pin older Sass version compatible with @import
          bundle install
          sudo apt-get update
          sudo apt-get install -y imagemagick python3 python3-pip
          pip3 install notebook nbconvert

      # 3️⃣ Setup Ruby and Bundler
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      # 4️⃣ Configure GitHub Pages
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      # 5️⃣ Build Jekyll site
      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      # 6️⃣ Upload Pages artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
